# Generated by Django 3.0.3 on 2020-03-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
