# Generated by Django 3.0.3 on 2020-03-06 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guild_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_id',
            field=models.SmallIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='loot',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loot',
            name='priority',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Item name'),
        ),
        migrations.CreateModel(
            name='Npc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='NPC name')),
                ('instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guild_management.Instance')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='loot',
            name='boss',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guild_management.Npc'),
            preserve_default=False,
        ),
    ]
