# Generated by Django 3.0.3 on 2020-03-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loot',
            name='exceptional',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
