# Generated by Django 3.0.3 on 2020-03-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='instance_appearance_order',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
