# Generated by Django 3.0.3 on 2020-03-07 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guild_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loot',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guild_management.Character'),
        ),
    ]
