# Generated by Django 3.0.3 on 2020-03-07 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guild_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='realm',
        ),
    ]
