# Generated by Django 3.0.3 on 2020-03-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='raid_count_override',
            new_name='attended_raids_override',
        ),
        migrations.AddField(
            model_name='character',
            name='eligible_raids_override',
            field=models.SmallIntegerField(default=0),
        ),
    ]
