# Generated by Django 3.0.3 on 2020-03-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild_management', '0002_auto_20200307_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='required',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
