# Generated by Django 3.0.3 on 2020-03-09 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guild_management', '0002_character_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loot',
            options={'ordering': ['-raid__instance_date', 'raid__instance__name', 'boss__instance_appearance_order', 'character__name', 'item__name'], 'verbose_name_plural': 'loot'},
        ),
        migrations.AlterModelOptions(
            name='npc',
            options={'ordering': ['instance_appearance_order', 'name']},
        ),
    ]
